apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello2-rancher
  namespace: hello-rancher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-rancher
  template:
    metadata:
      labels:
        app: hello-rancher
    spec:
      containers:
        - name: hello-rancher
          image: nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: web
            protocol: TCP

